# File này sẽ ghi đè các thiết lập trong docker-compose.yml cho môi trường production
services:
  db:
    ports: []
    restart: always

  backend:
    volumes: []
    restart: always
    environment:
      - FLASK_ENV=production

  frontend:
    volumes: []
    restart: always
    environment:
      - NODE_ENV=production