server {
  listen 80;
  server_name api.thinhsoft.test;

  location / {
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_pass         http://backend_upstream;
  }

  if ($request_method = OPTIONS) { return 204; }
}

server {
  listen 443 ssl http2;
  server_name api.thinhsoft.test;

  ssl_certificate     /etc/nginx/certs/thinhsoft.test+1.pem;
  ssl_certificate_key /etc/nginx/certs/thinhsoft.test+1-key.pem;

  location / {
    proxy_pass http://backend_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}