name: '🚀 Deploy to Server'

on:
  push:
    branches: [ deployment ]
  workflow_dispatch: {}

jobs:
  deploy:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add .env to api
        env:
          API_ENV: ${{ secrets.API_ENV }}
        working-directory: api
        run: |
          printf "%s\n" "$API_ENV" > .env

      - name: Install Composer dependencies
        working-directory: api
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Generate application key
        working-directory: api
        run: php artisan key:generate

      - name: Run Laravel migrations
        working-directory: api
        run: php artisan migrate --force --no-interaction

      - name: Add .env to web
        env:
          WEB_ENV: ${{ secrets.WEB_ENV }}
        working-directory: web
        run: |
          printf "%s\n" "$WEB_ENV" > .env

      - name: Install frontend dependencies
        working-directory: web
        run: npm ci

      - name: Build Next.js frontend
        working-directory: web
        run: npm run build

      - name: Copy files
        working-directory: web
        run: |
          rsync -av --delete ./ /var/www/portfolio/

      - name: Optimize Laravel
        run: |
          cd /var/www/portfolio/api
          php artisan optimize:clear
          php artisan optimize

      - name: Serve Next.js frontend
        run: |
          cd /var/www/portfolio/web
          pm2 start npm --name "web" -- run start